import { createClient } from '@supabase/supabase-js';

// PUBLIC_INTERFACE
// Initializes and exports the Supabase client for authentication and database operations.
// NOTE: You must replace the placeholders below with your actual Supabase Project URL and the public anon key.
// If you see 'failed to fetch' during signup/auth, it means authentication calls are not reaching Supabase API.
// Common causes:
//  1. Incorrect supabaseUrl or supabaseAnonKey (still set to YOUR_SUPABASE_URL or YOUR_SUPABASE_ANON_KEY)
//  2. The Supabase project has not added your frontend's domain (e.g. http://localhost:3000) to "Auth > Settings > Redirect URLs" or CORS settings
//  3. Network issues or firewall blocking the browser requests to api.supabase.co URLs
//  4. Key is revoked or project is paused
//  5. HTTPS misconfiguration in Project URL or invalid certificate

/*
 * SUPABASE CLIENT CONFIGURATION (autogenerated warning & template structure)
 *
 * --- IMPORTANT ---
 * You must set your Supabase Project URL and anon/public API key in one of these ways:
 * (Recommended for security) - Create a ".env" file in the project root and define:
 *   REACT_APP_SUPABASE_URL=your-supabase-url-here
 *   REACT_APP_SUPABASE_ANON_KEY=your-anon-key-here
 * OR: You may insert them directly below (not recommended for production!).
 *
 * See https://app.supabase.com/project/_/settings/api to fetch your config keys.
 *
 * Failing to configure these properly will cause all authentication and DB calls to fail with 'failed to fetch'!
 *
 * For dev and production, confirm:
 *   - Auth > URL Configuration has "Allowed Redirect URLs" set to http://localhost:3000 and all your deployed URLs
 *   - CORS settings allow requests from your frontend origin
 */

const supabaseUrl = process.env.REACT_APP_SUPABASE_URL || 'https://YOUR_SUPABASE_URL.supabase.co'; // <--- Set env var or replace
const supabaseAnonKey = process.env.REACT_APP_SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY'; // <--- Set env var or replace

if (
  !process.env.REACT_APP_SUPABASE_URL || !process.env.REACT_APP_SUPABASE_ANON_KEY ||
  supabaseUrl.includes('YOUR_SUPABASE_URL') ||
  supabaseAnonKey === 'YOUR_SUPABASE_ANON_KEY'
) {
  // eslint-disable-next-line no-console
  console.warn(
    '[Supabase] WARNING: Supabase credentials not set!\\n' +
      'Authentication requests WILL FAIL with "failed to fetch".' +
      '\\nSet REACT_APP_SUPABASE_URL and REACT_APP_SUPABASE_ANON_KEY in a .env file at project root, or directly in src/supabaseClient.js.\\n' +
      'See https://app.supabase.com/project/_/settings/api to get the correct values.' +
      '\\nCommon causes of broken signup:\n' +
      ' 1. Credentials not set or left as placeholders\n' +
      ' 2. Not added your frontend URL to Supabase Redirect URLs and CORS settings\n' +
      ' 3. Project paused, invalid key, or misconfigured HTTPS'
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
